baseurl = "https://ptstratx.github.io/wiki/"
canonifyurls = true
googleAnalytics = ""
languageCode = "en-us"
metadataformat = "yaml"
publishDir = "docs"
theme = "hugo-material-docs"
title = "PTStratX Wiki"
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
[[menu.main]]
name = "Roadmap"
url = "roadmap/"
weight = 4
[[menu.main]]
name = "Adding content"
url = "adding-content/"
weight = 3
[[menu.main]]
name = "Getting started"
url = "getting-started/"
weight = 2
[[menu.main]]
name = "Material"
url = "/"
weight = 1
[params]
author = "Digitalcraftsman"
copyright = "Released under the MIT license"
custom_css = []
custom_js = []
description = "A material design theme for documentations."
favicon = ""
highlight_css = ""
logo = "images/logo.png"
permalink = "#"
provider = "GitHub"
repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"
version = "1.0.0"
[params.font]
code = "Ubuntu Mono"
text = "Ubuntu"
[params.palette]
accent = "teal"
primary = "red"
[social]
email = "hello@email.com"
github = "digitalcraftsman"
twitter = ""
